<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>vala</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^\s*/\*|^(?![^{]*?//|[^{]*?/\*(?!.*?\*/.*?\{)).*?\{\s*($|//|/\*(?!.*?\*/.*\S))</string>
	<key>foldingStopMarker</key>
	<string>^\s*\*/|^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~C</string>
	<key>name</key>
	<string>Vala</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>///</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.source.vala</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.block.documentation.source.vala</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(&lt;/?)(?:([-_a-zA-Z0-9]+)((:)))?([-_a-zA-Z0-9:]+)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.source.vala</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.namespace.source.vala</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.source.vala</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.namespace.source.vala</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.localname.source.vala</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(/?&gt;)</string>
					<key>name</key>
					<string>keyword.other.documentation.source.vala</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.other.attribute-name.namespace.source.vala</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.other.attribute-name.source.vala</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator.namespace.source.vala</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>entity.other.attribute-name.localname.source.vala</string>
								</dict>
							</dict>
							<key>match</key>
							<string> (?:([-_a-zA-Z0-9]+)((:)))?([_a-zA-Z-]+)=</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#doubleQuotedString</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#singleQuotedString</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?x)^\s*
((?:\b(?:new|public|protected|internal|private|abstract|sealed|static)\b\s)*)
(class)\s+
([A-Za-z_]\w+)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.source.vala</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.source.vala</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class.source.vala</string>
				</dict>
			</dict>
			<key>end</key>
			<string>{</string>
			<key>name</key>
			<string>meta.definition.class.source.vala</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#classInheritance</string>
				</dict>
			</array>
		</dict>
		<!--
		Disabled because it causes some lines to be interpreted incorrectly, for example:
			else if (c == ')')
		--->
		<!--
		<dict>
			<key>begin</key>
			<string>(?x)^\s*	                                                                            # start of line
((?:\b(?:new|public|protected|internal|private|static|virtual|sealed|override|abstract|extern)\b\s*)*) 		# method-modifiers
\b((?:\w+\.)*[A-Za-z_]\w*)\b\s*	                                                                      		# type
(operator)\s+        			                                                                      		# operator overload
((?:\+|-|!|~|\+\+|--|true|false|\*|/|%|\&amp;|\||\^|&lt;&lt;|&gt;&gt;|==|!=|&lt;|&gt;|&lt;=|&gt;=)\s*)	                          		# operator name
(?=\()</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.source.vala</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.source.vala</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.source.vala</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.source.vala</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>meta.definition.operator.source.vala</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#statementRemainder</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?x)^\s*	                                                                        # start of line
((?:\b(?:new|public|protected|internal|private|static|virtual|sealed|override|abstract|extern)\b\s*)*) 	# method-modifiers
\b((?:\w+\.)*[A-Za-z_]\w*)\b\s*		                                                                  	# type
([A-Za-z_]\w*)\s*					         			                                   			 	# name
(?=\()</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.source.vala</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.source.vala</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.source.vala</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>meta.definition.method.source.vala</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#statementRemainder</string>
				</dict>
			</array>
		</dict>
		-->
		<dict>
			<key>match</key>
			<string>\b(true|false|null|this|base)\b</string>
			<key>name</key>
			<string>constant.language.source.vala</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)(L|l|UL|ul|u|U|F|f|ll|LL|ull|ULL)?\b</string>
			<key>name</key>
			<string>constant.numeric.source.vala</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|else|while|for|foreach|do|return|continue|break|switch|case|default|goto|throw|try|catch|finally|lock|yield|throws|requires|ensures)\b</string>
			<key>name</key>
			<string>keyword.control.source.vala</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(var|new|is|typeof|sizeof|override|in|out|ref|params|as)\b</string>
			<key>name</key>
			<string>keyword.operator.source.vala</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(delegate|in|set|get)\b</string>
			<key>name</key>
			<string>keyword.other.source.vala</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(internal|public|protected|private|static|const|new|var|abstract|override|extern|async|inline|weak|unowned|owned|global|dynamic|volatile)\b</string>
			<key>name</key>
			<string>storage.modifier.source.vala</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#doubleQuotedStringLiteral</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#doubleQuotedString</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#singleQuotedString</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.using.source.vala</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.package.source.vala</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(using)\s+([^ ;]*);</string>
			<key>name</key>
			<string>meta.keyword.using.source.vala</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#builtinTypes</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.namespace.source.vala</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.namespace.source.vala</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(namespace)\s+([^ ]+)(?:\s*{)?$</string>
			<key>name</key>
			<string>meta.keyword.namespace.source.vala</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.source.vala</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(#)\s*(if|else|elif|endif|define|undef|warning|error|line|region|endregion)\b</string>
			<key>name</key>
			<string>meta.preprocessor.source.vala</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>builtinTypes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(double|float|bool|char|uchar|short|ushort|int|uint|long|ulong|size_t|ssize_t|int8|uint8|int16|uint16|int32|uint32|int64|uint64|unichar|object|string|void|class|struct|enum|construct|interface|errordomain)\b</string>
					<key>name</key>
					<string>storage.type.source.vala</string>
				</dict>
			</array>
		</dict>
		<key>classInheritance</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>:</string>
					<key>end</key>
					<string>(?={)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>storage.type.source.vala</string>
								</dict>
							</dict>
							<key>match</key>
							<string>\s*,?([A-Za-z_]\w*)\b</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.source.vala</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.source.vala</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.source.vala</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(//).*$\n?</string>
					<key>name</key>
					<string>comment.line.double-slash.source.vala</string>
				</dict>
			</array>
		</dict>
		<key>doubleQuotedString</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.source.vala</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.source.vala</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.source.vala</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.source.vala</string>
				</dict>
			</array>
		</dict>
		<key>doubleQuotedStringLiteral</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.source.vala</string>
				</dict>
			</dict>
			<key>match</key>
			<string>@"([^"]|"")*"</string>
			<key>name</key>
			<string>string.quoted.double.literal.source.vala</string>
		</dict>
		<key>singleQuotedString</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.source.vala</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.source.vala</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.xml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.source.vala</string>
				</dict>
			</array>
		</dict>
		<key>statementRemainder</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>end</key>
					<string>(?=\))</string>
					<key>name</key>
					<string>meta.definition.param-list.source.vala</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#builtinTypes</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.vala</string>
	<key>uuid</key>
	<string>1BA75B32-707C-11D9-A928-000D93589AF6</string>
</dict>
</plist>
